import axios, { AxiosInstance, AxiosError } from 'axios';
import https from 'node:https';
import type {
  JiraIssue, JiraSprint, JiraBoard,
  JiraSearchResult, JiraBoardResult, JiraSprintResult,
  JiraChangelog, JiraComment, JiraCommentResponse,
} from '../types';
import { Result, success, failure, fromHttpStatus } from '../types/result.types';
import { loadJiraConfig, JiraConfig } from '../config/jira.config';
import { isUserStory } from '../types/jira.types';

const httpsAgent = new https.Agent({ rejectUnauthorized: false });

const DEFAULT_AI_MARKERS = [
  // Explicit AI/agent mentions
  'Implementation started by automated agent',
  'agent IA',
  'dev IA',
  'développé par IA',
  'generated by AI',
  'AI agent',
  'AI-assisted',
  'copilot',
  'automated implementation',
  'code généré par IA',
  // Automated MR / CI-CD bot patterns
  'Merge Request',
  'merge request',
  'pull request',
  'auto-generated',
  'auto-merge',
  'bot commit',
  // Common AI tools signatures
  'GitHub Copilot',
  'ChatGPT',
  'Claude',
  'Cursor',
  'Codeium',
  'Tabnine',
  'Amazon CodeWhisperer',
  // French patterns
  'généré automatiquement',
  'implémentation automatique',
  'résolu par IA',
  'traité par agent',
  'assisté par IA',
] as const;

export function getAIMarkers(): string[] {
  const envMarkers = (process.env.AI_AGENT_MARKERS ?? '').split(',').map(s => s.trim()).filter(Boolean);
  return envMarkers.length > 0 ? envMarkers : [...DEFAULT_AI_MARKERS];
}

interface CacheEntry<T> {
  data: T;
  expiresAt: number;
}

export class JiraClient {
  private http: AxiosInstance;
  private config: JiraConfig;
  private cache = new Map<string, CacheEntry<unknown>>();

  constructor(config?: JiraConfig) {
    this.config = config ?? loadJiraConfig();
    this.http = axios.create({
      baseURL: this.config.baseUrl,
      headers: {
        Authorization: `Bearer ${this.config.token}`,
        'Content-Type': 'application/json',
      },
      timeout: 30000,
      httpsAgent,
    });
  }

  private getCached<T>(key: string): T | null {
    const entry = this.cache.get(key) as CacheEntry<T> | undefined;
    if (entry && entry.expiresAt > Date.now()) {
      return entry.data;
    }
    this.cache.delete(key);
    return null;
  }

  private setCache<T>(key: string, data: T): void {
    this.cache.set(key, {
      data,
      expiresAt: Date.now() + this.config.cacheTtlSeconds * 1000,
    });
  }

  invalidateCache(): void {
    this.cache.clear();
  }

  private async request<T>(path: string, cacheKey?: string): Promise<Result<T>> {
    if (cacheKey) {
      const cached = this.getCached<T>(cacheKey);
      if (cached) return success(cached);
    }

    try {
      const response = await this.http.get<T>(path);
      if (cacheKey) this.setCache(cacheKey, response.data);
      return success(response.data);
    } catch (err) {
      if (err instanceof AxiosError) {
        const status = err.response?.status ?? 0;
        const msg = err.response?.data?.errorMessages?.[0] ?? err.message;
        return fromHttpStatus(status, msg);
      }
      return failure('NETWORK_ERROR', String(err));
    }
  }

  private async post<T>(path: string, body: unknown): Promise<Result<T>> {
    try {
      const response = await this.http.post<T>(path, body);
      return success(response.data);
    } catch (err) {
      if (err instanceof AxiosError) {
        const status = err.response?.status ?? 0;
        const msg = err.response?.data?.errorMessages?.[0] ?? err.message;
        return fromHttpStatus(status, msg);
      }
      return failure('NETWORK_ERROR', String(err));
    }
  }

  // --- Projects ---

  async getProjects(): Promise<Result<Array<{ key: string; name: string; id: string }>>> {
    return this.request<Array<{ key: string; name: string; id: string }>>(
      '/rest/api/2/project',
      'projects',
    );
  }

  async validateConnection(): Promise<Result<{ displayName: string }>> {
    return this.request<{ displayName: string }>(
      '/rest/api/2/myself',
      undefined,
    );
  }

  setProjectKey(projectKey: string): void {
    this.config = { ...this.config, projectKey };
    this.cache.clear();
  }

  // --- Boards ---

  async getBoards(projectKey?: string): Promise<Result<JiraBoard[]>> {
    const key = projectKey ?? this.config.projectKey;
    const result = await this.request<JiraBoardResult>(
      `/rest/agile/1.0/board?projectKeyOrId=${key}`,
      `boards:${key}`
    );
    if (!result.success) return result;
    return success(result.data.values);
  }

  // --- Sprints ---

  async getSprints(boardId: number, state?: string): Promise<Result<JiraSprint[]>> {
    const stateParam = state ? `&state=${state}` : '';
    const cacheKey = `sprints:${boardId}:${state ?? 'all'}`;
    const cached = this.getCached<JiraSprint[]>(cacheKey);
    if (cached) return success(cached);

    const allSprints: JiraSprint[] = [];
    let startAt = 0;
    const pageSize = 50;

    // Paginate through all sprints
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const result = await this.request<JiraSprintResult & { isLast?: boolean }>(
        `/rest/agile/1.0/board/${boardId}/sprint?maxResults=${pageSize}&startAt=${startAt}${stateParam}`,
      );
      if (!result.success) return result;

      allSprints.push(...result.data.values);

      if (result.data.isLast !== false || result.data.values.length < pageSize) {
        break;
      }
      startAt += pageSize;
    }

    this.setCache(cacheKey, allSprints);
    return success(allSprints);
  }

  // --- Issues (paginated) ---

  async getSprintIssues(sprintId: number, fields?: string[]): Promise<Result<JiraIssue[]>> {
    const cacheKey = `sprint-issues:${sprintId}`;
    const cached = this.getCached<JiraIssue[]>(cacheKey);
    if (cached) return success(cached);

    const defaultFields = [
      'summary', 'status', 'issuetype', 'priority', 'assignee',
      'created', 'resolutiondate', 'issuelinks', 'subtasks',
      'labels', 'components', 'description', 'story_points',
    ];

    const allIssues: JiraIssue[] = [];
    let startAt = 0;
    const maxPerPage = 50;

    while (true) {
      const result = await this.post<JiraSearchResult>('/rest/api/2/search', {
        jql: `sprint = ${sprintId} ORDER BY key ASC`,
        startAt,
        maxResults: maxPerPage,
        fields: fields ?? defaultFields,
      });

      if (!result.success) return result;

      allIssues.push(...result.data.issues);
      startAt += result.data.issues.length;

      if (startAt >= result.data.total) break;
    }

    this.setCache(cacheKey, allIssues);
    return success(allIssues);
  }

  async getSprintUserStories(sprintId: number): Promise<Result<JiraIssue[]>> {
    const result = await this.getSprintIssues(sprintId);
    if (!result.success) return result;
    return success(result.data.filter(isUserStory));
  }

  // --- Kanban: issues by date range (paginated) ---

  async getIssuesByJQL(jql: string, cacheKey: string): Promise<Result<JiraIssue[]>> {
    const cached = this.getCached<JiraIssue[]>(cacheKey);
    if (cached) return success(cached);

    const defaultFields = [
      'summary', 'status', 'issuetype', 'priority', 'assignee',
      'created', 'resolutiondate', 'issuelinks', 'subtasks',
      'labels', 'components', 'description', 'story_points',
    ];

    const allIssues: JiraIssue[] = [];
    let startAt = 0;
    const maxPerPage = 50;

    while (true) {
      const result = await this.post<JiraSearchResult>('/rest/api/2/search', {
        jql,
        startAt,
        maxResults: maxPerPage,
        fields: defaultFields,
      });

      if (!result.success) return result;

      allIssues.push(...result.data.issues);
      startAt += result.data.issues.length;

      if (startAt >= result.data.total) break;
    }

    this.setCache(cacheKey, allIssues);
    return success(allIssues);
  }

  async getKanbanIssues(projectKey: string, startDate: string, endDate: string): Promise<Result<JiraIssue[]>> {
    const jql = `project = "${projectKey}" AND updated >= "${startDate}" AND updated <= "${endDate}" ORDER BY key ASC`;
    return this.getIssuesByJQL(jql, `kanban-issues:${projectKey}:${startDate}:${endDate}`);
  }

  /** Issues matching AI-agent markers in comments or ai-assisted label, scoped by sprint or date range */
  async getAIAgentIssues(scope: { sprintId: number } | { projectKey: string; startDate: string; endDate: string }): Promise<Result<JiraIssue[]>> {
    const markers = getAIMarkers();

    // Build JQL: labels = "ai-assisted" OR (comment ~ "marker1" OR comment ~ "marker2" OR ...)
    const commentFilter = markers.map(m => `comment ~ "${m}"`).join(' OR ');
    const aiFilter = `labels = "ai-assisted" OR ${commentFilter}`;

    let jql: string;
    let cacheKey: string;

    if ('sprintId' in scope) {
      jql = `sprint = ${scope.sprintId} AND (${aiFilter}) ORDER BY key ASC`;
      cacheKey = `ai-agent-issues:sprint:${scope.sprintId}`;
    } else {
      jql = `project = "${scope.projectKey}" AND updated >= "${scope.startDate}" AND updated <= "${scope.endDate}" AND (${aiFilter}) ORDER BY key ASC`;
      cacheKey = `ai-agent-issues:kanban:${scope.projectKey}:${scope.startDate}:${scope.endDate}`;
    }

    return this.getIssuesByJQL(jql, cacheKey);
  }

  // --- Single issue with changelog ---

  async getIssueWithChangelog(issueKey: string): Promise<Result<JiraIssue>> {
    return this.request<JiraIssue>(
      `/rest/api/2/issue/${issueKey}?expand=changelog&fields=summary,status,issuetype,priority,assignee,created,resolutiondate,issuelinks,subtasks,labels,components,description,story_points`,
      `issue-changelog:${issueKey}`
    );
  }

  /** MT5: Batch fetch issues with changelog via JQL expand=changelog (avoids N+1 requests) */
  async getIssuesWithChangelogByJQL(jql: string, cacheKey: string): Promise<Result<JiraIssue[]>> {
    const cached = this.getCached<JiraIssue[]>(cacheKey);
    if (cached) return success(cached);

    const defaultFields = [
      'summary', 'status', 'issuetype', 'priority', 'assignee',
      'created', 'resolutiondate', 'issuelinks', 'subtasks',
      'labels', 'components', 'description', 'story_points',
    ];

    const allIssues: JiraIssue[] = [];
    let startAt = 0;
    const maxPerPage = 50;

    while (true) {
      const result = await this.post<JiraSearchResult & { issues: JiraIssue[] }>('/rest/api/2/search', {
        jql,
        startAt,
        maxResults: maxPerPage,
        fields: defaultFields,
        expand: ['changelog'],
      });

      if (!result.success) return result;

      for (const issue of result.data.issues) {
        allIssues.push(issue);
        // Populate individual issue changelog cache too
        this.setCache(`issue-changelog:${issue.key}`, issue);
      }

      startAt += result.data.issues.length;
      if (startAt >= result.data.total) break;
    }

    this.setCache(cacheKey, allIssues);
    return success(allIssues);
  }

  // --- Issue comments ---

  async getIssueComments(issueKey: string): Promise<Result<JiraComment[]>> {
    const cacheKey = `issue-comments:${issueKey}`;
    const cached = this.getCached<JiraComment[]>(cacheKey);
    if (cached) return success(cached);

    const result = await this.request<JiraCommentResponse>(
      `/rest/api/2/issue/${issueKey}/comment?maxResults=1000&orderBy=created`,
    );
    if (!result.success) return result;

    const comments = result.data.comments;
    this.setCache(cacheKey, comments);
    return success(comments);
  }

  /** Find the earliest comment that matches any AI marker. Returns the ISO date or null. */
  async findFirstAICommentDate(issueKey: string): Promise<string | null> {
    const commentsResult = await this.getIssueComments(issueKey);
    if (!commentsResult.success) return null;

    const markers = getAIMarkers();
    const lowerMarkers = markers.map(m => m.toLowerCase());

    // Comments are ordered by created ASC
    for (const comment of commentsResult.data) {
      const bodyLower = comment.body.toLowerCase();
      if (lowerMarkers.some(marker => bodyLower.includes(marker))) {
        return comment.created;
      }
    }

    return null;
  }

  // --- Search ---

  async searchIssues(jql: string, fields?: string[], maxResults = 50): Promise<Result<JiraIssue[]>> {
    const result = await this.post<JiraSearchResult>('/rest/api/2/search', {
      jql,
      maxResults,
      fields: fields ?? ['summary', 'status', 'issuetype', 'priority'],
    });
    if (!result.success) return result;
    return success(result.data.issues);
  }

  // --- Config accessors ---

  getConfig(): JiraConfig {
    return this.config;
  }

  getProjectKey(): string {
    return this.config.projectKey;
  }
}

// Singleton instance
let clientInstance: JiraClient | null = null;

export function getJiraClient(config?: JiraConfig): JiraClient {
  if (!clientInstance || config) {
    clientInstance = new JiraClient(config);
  }
  return clientInstance;
}

export function resetJiraClient(): void {
  clientInstance = null;
}

export function hasJiraClient(): boolean {
  return clientInstance !== null;
}
